version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: cakto_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: cakto_db
      MYSQL_USER: senior_cakto
      MYSQL_PASSWORD: queroMuitoPassar
      MYSQL_ROOT_PASSWORD: tomaraQueEuPasse
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  mysql_data:
